### ISSUE TITLE
See if restaurant is currently open

### ISSUE THREAD

**Issue by mcginnis92** [haganka/Dining-in-the-Rough#22]
DOD:

Results render section shows if it is currently open or closed

**Comment by cybernetck** [comment]
We can use the following value from the API 'hours[x].is_open_now' - which is a boolean that lets us know if a place is open or not at the time that the search is run - to indicate on the map if the place is open or closed.  Perhaps we can use custom markers instead of the Google Standard red ones so a user can understand if a place is open or not, as soon as they get their search results?
